### ISSUE TITLE
调用 history.undo 报错

### ISSUE THREAD

**Issue by tiancihe** [antvis/X6#1359]
### Expected Behavior

`history.undo` 能正常撤销操作

### Current Behavior

执行 `history.undo` 报错

### Steps To Reproduce

https://codesandbox.io/s/history-undo-failed-hnsmh

1. 连接两个节点
2. 触发 `edge:connected` 事件
3. 执行 `history.undo` 报错，页面崩溃

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->

TypeError: Cannot read properties of null (reading 'prop')
    at HistoryManager.executeCommand (https://hnsmh.csb.app/node_modules/@antv/x6/es/graph/history.js:173:14)

    at HistoryManager.revertCommand (https://hnsmh.csb.app/node_modules/@antv/x6/es/graph/history.js:141:12)

    at HistoryManager.undo (https://hnsmh.csb.app/node_modules/@antv/x6/es/graph/history.js:57:14)

    at eval (eval at <anonymous> (https://codesandbox.io/static/js/sandbox-startup.56e143351.js:1:17696), <anonymous>:1:15)

    at eval (<anonymous>)

    at Object.<anonymous> (https://codesandbox.io/static/js/sandbox-startup.56e143351.js:1:17696)

    at https://codesandbox.io/static/js/sandbox-startup.56e143351.js:1:9331

    at Array.forEach (<anonymous>)

    at L (https://codesandbox.io/static/js/sandbox-startup.56e143351.js:1:9294)

    at $ (https://codesandbox.io/static/js/sandbox-startup.56e143351.js:1:9503)
```

</p></details>

### Your Environment

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by tiancihe** [comment]
> 这里存在一个问题，添加父节点的步骤，如果 undo 删除父节点，同时会将子节点一直删除，然后继续 undo connected，就会出现报错，处理方式如下：
> 
> ```ts
> graph.undo({deep: false, dryrun: true})
> ```

@NewByVector 这两个参数不管什么情况下都可以传，并且 undo 的执行结果都会符合预期吗？如果不是的话，要支持画布撤销和重做不就需要根据具体执行的交互操作来判断需不需要传这两个参数么，这个很难处理吧

**Comment by NewByVector** [comment]
@tiancihe 现在看起来就父子节点删除有这个问题，还没有很好的方法在x6中规避这个为
