### ISSUE TITLE
nextjs12.0.4下报错ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by lichong-a** [antvis/X6#2767]
### 问题描述

开发环境没有问题，next build时发生报错：
```cmd
> Build error occurred
ReferenceError: navigator is not defined
    at Object.<anonymous> (D:\WorkSpaces\htmlProjects\one\node_modules\@antv\x6\lib\util\platform\index.js:4:10)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\WorkSpaces\htmlProjects\one\node_modules\@antv\x6\lib\util\polyfill\index.js:8:18)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10) {
  type: 'ReferenceError'
}
error Command failed with exit code 1.
```

诡异的是组件目录在src/components下时没有问题，但在src/pages/**/components下才会有以上报错

### 重现链接

无

### 重现步骤

next build

### 预期行为

预期效果是编译通过

### 平台

- 操作系统: Windows11
- 网页浏览器: Google Chrome106
- X6 版本: 1.32.11
- nodejs：16.14.0
- nextjs：12.0.4
- react：17.0.2

**Comment by NewByVector** [comment]
请更新 x6 到  1.34.4 版本。
