### ISSUE TITLE
vue类型节点内部国际化依赖报错

### ISSUE THREAD

**Issue by wtjperi2003** [antvis/X6#3954]
### Describe the bug

vue节点内部，使用`const {t}=useI18n();`运行时会报下列错误:
```javascript
runtime-core.esm-bundler.js:221 Uncaught SyntaxError: Need to install with `app.use` function (at message-compiler.esm-bundler.js:54:19)
    at createCompileError (message-compiler.esm-bundler.js:54:19)
    at createI18nError (vue-i18n.esm-bundler.js:100:12)
    at useI18n (vue-i18n.esm-bundler.js:2219:15)
    at setup (dynamicChart.vue:19:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7236:25)
    at setupComponent (runtime-core.esm-bundler.js:7197:36)
    at mountComponent (runtime-core.esm-bundler.js:5599:7)
    at processComponent (runtime-core.esm-bundler.js:5565:9)
    at patch (runtime-core.esm-bundler.js:5040:11)
```
实际上再main.ts里已经app.use(i18n)了。

### Your Example Website or App

暂时没有

### Steps to Reproduce the Bug or Issue

vue3项目安装"vue-i18n": "9"依赖，main.ts里安装[文档](https://vue-i18n.intlify.dev/guide/installation.html)启用:
```javascript
import { createApp } from 'vue'
import { createI18n } from 'vue-i18n'

const i18n = createI18n({
  // something vue-i18n options here ...
})

const app = createApp({
  // something vue options here ...
})

app.use(i18n)
app.mount('#app')
```
然后自定义一个vue节点，再里面`const {t}=useI18n();` 。
然后再graph里添加该节点

### Expected behavior

能正常使用

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 2.11.1]

**Comment by lloydzhou** [comment]
vue3请使用teleport模式渲染节点

**Comment by whenTheMorningDark** [comment]
老哥你解决了吗？我也遇到了相同问题 @wtjperi2003

**Comment by whenTheMorningDark** [comment]
> vue3请使用teleport模式渲染节点

有例子吗？

**Comment by NewByVector** [comment]
官网例子就是使用 `teleport` 模式。

**Comment by fengxiaodong28** [comment]
@lloydzhou vue2的 可以使用teleport 吗？

**Comment by lloydzhou** [comment]
@fengxiaodong28 
teleport是vue3的一个内置的组件。vue2中没有
