### ISSUE TITLE
yarn bootstrap 在windows10 操作系统下报错

### ISSUE THREAD

**Issue by awehook** [antvis/X6#925]
Error: Cannot find module 'D:\coding\fe\X6\node_modules\node_modules\npm-run-all\bin\run-s\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {

很奇怪，这里报错的路径里面有两层node_modules, 我让朋友在他电脑上试了下，也有同样的问题

**Comment by zaiMoe** [comment]
这里有重复的问题 https://github.com/antvis/X6/issues/809

**Comment by awehook** [comment]
> 这里有重复的问题 #809

非常感谢
