### ISSUE TITLE
包含 rotatableNode 的 NodeView 计算 BBox 失败

### ISSUE THREAD

**Issue by OpportunityLiu** [antvis/X6#948]
### Current Behavior

包含 rotatableNode 的 NodeView 计算 BBox 失败

### Steps To Reproduce

https://codesandbox.io/s/vigilant-bogdan-7w1bb

<details><summary>Error Message & Stack Trace</summary><p>

```txt
TypeError: node.getAttribute is not a function
    at Object.getMatrixByElementAttr (https://m57ur.csb.app/node_modules/@antv/x6/es/util/dom/geom.js:149:30)

    at Cache.getMatrix (https://m57ur.csb.app/node_modules/@antv/x6/es/view/cache.js:38:41)

    at NodeView.getMatrixOfElement (https://m57ur.csb.app/node_modules/@antv/x6/es/view/cell.js:229:23)

    at NodeView.getUnrotatedBBoxOfElement (https://m57ur.csb.app/node_modules/@antv/x6/es/view/cell.js:262:25)

    at Object.getViewBBox (https://m57ur.csb.app/node_modules/@antv/x6/es/registry/tool/util.js:18:66)

    at Boundary.update (https://m57ur.csb.app/node_modules/@antv/x6/es/registry/tool/boundary.js:35:21)

    at Boundary.onRender (https://m57ur.csb.app/node_modules/@antv/x6/es/registry/tool/boundary.js:28:10)

    at Boundary.render (https://m57ur.csb.app/node_modules/@antv/x6/es/view/tool.js:270:12)

    at ToolsView.config (https://m57ur.csb.app/node_modules/@antv/x6/es/view/tool.js:107:14)

    at NodeView.addTools (https://m57ur.csb.app/node_modules/@antv/x6/es/view/cell.js:498:13)

    at NodeView.renderTools (https://m57ur.csb.app/node_modules/@antv/x6/es/view/cell.js:535:10)

    at NodeView.render (https://m57ur.csb.app/node_modules/@antv/x6/es/view/node.js:136:10)

    at NodeView.confirmUpdate (https://m57ur.csb.app/node_modules/@antv/x6/es/view/node.js:62:12)

    at Renderer.updateView (https://m57ur.csb.app/node_modules/@antv/x6/es/graph/renderer.js:284:17)

    at Renderer.updateViewsBatch (https://m57ur.csb.app/node_modules/@antv/x6/es/graph/renderer.js:352:33)

    at Renderer.updateViews (https://m57ur.csb.app/node_modules/@antv/x6/es/graph/renderer.js:292:21)

    at Renderer.requestViewUpdate (https://m57ur.csb.app/node_modules/@antv/x6/es/graph/renderer.js:233:24)

    at Renderer.renderView (https://m57ur.csb.app/node_modules/@antv/x6/es/graph/renderer.js:715:12)

    at Renderer.onCellAdded (https://m57ur.csb.app/node_modules/@antv/x6/es/graph/renderer.js:86:12)

    at Object.apply (https://m57ur.csb.app/node_modules/@antv/x6/es/util/function/function.js:51:19)

    at Object.call (https://m57ur.csb.app/node_modules/@antv/x6/es/common/events.js:80:47)

    at Model.trigger (https://m57ur.csb.app/node_modules/@antv/x6/es/common/events.js:58:28)

    at Model.notify (https://m57ur.csb.app/node_modules/@antv/x6/es/model/model.js:29:10)

    at Rect.notify (https://m57ur.csb.app/node_modules/@antv/x6/es/model/cell.js:135:13)

    at eval (https://m57ur.csb.app/node_modules/@antv/x6/es/model/collection.js:91:16)
```

</p></details>

### Additional Context

#936 引入的 BUG
`getMatrixByElementAttr` 要求 `elem` 是 `target` 的子节点，但在 `Cache.prototype.getMatrix` 中，计算节点 BBox 时，elem 是 node view 的 container，rotatableNode 存在时，是 container 的子节点

### Your Environment

- x6: 1.20.0
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]

**Comment by OpportunityLiu** [comment]
不过 rotatableNode 这个功能目前应该是 undocumented，我也是看了源码才发现这个功能的

**Comment by NewByVector** [comment]
这个在下个版本会删除，不用考虑这个了。
